name: Test

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: wei18/local-composite-action/.github/composite-actions/example@3e6f017c4bf7f9451fc0b6d987d47507fa401aa3 # main
